config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'fetch_cricinfo_data#index'
  resources :users do
  	member do
  		get 'enter_meaning'
  		get 'show_meaning_data'
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fetch_cricinfo_datum.rb
class FetchCricinfoDatum < ApplicationRecord
	def self.get_score(url)
		return Net::HTTP.get(URI.parse(url))
	end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fetch_cricinfo_data_controller.rb
class FetchCricinfoDataController < ApplicationController
	def index
		@get_score = JSON.parse(Hash.from_xml(FetchCricinfoDatum.get_score('http://static.cricinfo.com/rss/livescores.xml')).to_json)
		Rails.logger.debug "get_Scores #{@get_score}"
	end
end

app/controllers/meanings_data_controller.rb
class MeaningsDataController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_meaning_data
    @data = GetMeaningsData.get_words_total_data([params[:word_name]])
  end

  def enter_meaning
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fetch_cricinfo_data_helper.rb
module FetchCricinfoDataHelper
end

app/helpers/meanings_data_helper.rb
module MeaningsDataHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fetch_cricinfo_data/index.html.erb
<% @get_score['rss']['channel']['item'].each do |match| %>
	<h4>Match Score: <%= match["title"] %></h4>
<% end %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Get Live Cricket Scores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
	</div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/enter_meaning.html.erb
<div class="row">
	<%= form_tag(show_meaning_data_user_path, :method => 'get') do %>
	  <div class="col-lg-12 col-lg-offset-4"><%= label_tag(:word_name, "Search for word:") %></div>
	  <div class="col-md-8 col-md-push-4"><%= text_field_tag(:word_name) %></div>
	  <%= submit_tag("Search",class: "btn btn-primary") %>
	<% end %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_meaning_data.html.erb
<% unless @data.blank? %>
	<p>Meaning Data</p>
	<% @data.each do |main_word, total_data| %>
		<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2 class="panel-title">Word: <%= main_word.capitalize %></h2>
			</div>
			<div class="panel-body">
				<% total_data.each do |word_key,word_data| %>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title"><%= word_key %></h3>
						</div>
						<div class="panel-body">
							<% word_data.each do |word| %>
								<ul class="list-group">
									<li class="list-group-item">
										<% word.each do |key,value| %>
										<div>
											<h4 class="list-group-item-heading"><%=key%></h4>
											<h5 class="list-group-item-text list-move-up"><em><%=value%></em></h5></br>
										</div>
										<% end unless word.nil?%>
									</li>
								</ul>
							<% end unless word_data.nil?%>
						</div>
					</div>
				<% end unless total_data.nil? %>
			</div>
		</div>
		</div>
	<% end %>
<% end %>